version: '3.7'

services:
    project_redis:
        container_name: project_redis
        hostname: redis
        image: redis:latest
        command: --port ${REDIS_PORT}
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        restart: always

    api:
        container_name: api
        depends_on:
            - project_redis
            - worker 
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
        - "${API_PORT}:${API_PORT}"
        working_dir: /home/MLServiceProj
        volumes:
            - ./:/home/MLServiceProj
        links:
            - project_redis
        command: uvicorn backend.main:app --host ${API_HOST} --port ${API_PORT} --reload

    worker_init_container:
        container_name: worker_init_container
        depends_on:
            - project_redis
        build:
            context: ./
            dockerfile: ./Dockerfile   
        volumes:
            - ./:/home/MLServiceProj
        command: python3.10 /home/MLServiceProj/worker.py
        env_file:
            .env

    worker:
        container_name: worker
        depends_on:
            project_redis:
                condition: service_started
            worker_init_container:
                condition: service_completed_successfully
        build:
            context: ./
            dockerfile: ./Dockerfile   
        volumes:
            - ./:/home/MLServiceProj
        command: rq worker --url redis://project_redis:${REDIS_PORT}
        env_file:
            .env 
    
    dash_frontend:
        container_name: dash_frontend
        build:
            context: ./
            dockerfile: ./Dockerfile            
        ports:
            - "${FRONTEND_EXPOSED_PORT}:${FRONTEND_PORT}"
        volumes:
            - ./:/home/MLServiceProj
        working_dir: /home/MLServiceProj
        command: python3.10 -m frontend.app